apiVersion: apps/v1
kind: Deployment
metadata:
  name: night-rider
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: night-rider
        image: sheldonwl/knight-rider-demo:1.0
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh","-c","python - <<END \nimport blinkt \nblinkt.clear() \nblinkt.show() \nEND"]
      imagePullSecrets:
      - name: regcred
